name: menu_repository
description: A repository managing the menu domain.
version: 0.1.0+1
publish_to: none

environment:
  sdk: ^3.11.0
  flutter: ^3.41.2

dependencies:
  api_client:
    path: ../api_client
  flutter:
    sdk: flutter
  very_yummy_coffee_models:
    path: ../very_yummy_coffee_models

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4
  very_good_analysis: ^10.0.0
