name: very_yummy_coffee_ui
description: A shared UI package for all the stylings and themes for Very Yummy Coffee.
version: 0.1.0+1
publish_to: none

environment:
  sdk: ^3.11.0
  flutter: ^3.41.2

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4
  very_good_analysis: ^10.0.0

flutter:
  fonts:
    - family: IBM Plex Sans
      fonts:
        - asset: assets/fonts/IBMPlexSans-Regular.ttf
          weight: 400
        - asset: assets/fonts/IBMPlexSans-Italic.ttf
          weight: 400
          style: italic
        - asset: assets/fonts/IBMPlexSans-Light.ttf
          weight: 300
        - asset: assets/fonts/IBMPlexSans-Medium.ttf
          weight: 500
        - asset: assets/fonts/IBMPlexSans-Bold.ttf
          weight: 700
